lab08:
  target: dev

  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: "{{ env_var('CLICKHOUSE_HTTP_PORT', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      schema: "{{ env_var('CLICKHOUSE_DB', 'default') }}"
      secure: false
